### ISSUE TITLE
Summing Elements of Array

### ISSUE THREAD

**Issue by tbraun96** [altimesh/hybridizer-basic-samples#49]
Hello,

When I've programmed CUDA via c++, there existed an AtomicAdd function. Is there a working implementation of this in Hybridizer? Suppose I have an array[] = {5,4,3} and I want to sum each value to get a single value (i.e., 5+4+3 = 12). Here is what I have thus far, but does not return the correct value:

[EntryPoint]
        private static void SumAll(double[] a, double b, int N)
        {
            for (int k = threadIdx.x + blockDim.x * blockIdx.x; k < N; k += blockDim.x * gridDim.x)
            {
                b += a[k];
            }
        }

As you can see, "b" should stores the sum. However, this does not work. Under normal circumstances, I would use AtomicAdd and could successfully Sum all elements of an array. How would you go about solving this problem?

**Comment by JeWaVe** [comment]
as discussed by email, it's already possible to use atomicAdd with Hybridizer (IntrinsicFunction / builtin file should do the job)
We'll add that for next release as enhancement.

**Comment by tbraun96** [comment]
Perfect. Thank you! I believe making such implementations will further incentivize other developers to choose Hybridizer over other GPU API's.

**Comment by JeWaVe** [comment]
Fixed in our latest version (not released yet : http://www.altimesh.com/download_msi/) 

- eased adding builtin files by introducing an item template. (right click on generated project -> Add -> New Item -> Builtin

- Builtin files now have an xsd schema descriptor ("http://www.altimesh.com/2018/builtins-schema") which you can add to your schema sets in visual studio to get autocompletion. 

- A sample with Interlocked.Add (int32) has been added https://github.com/altimesh/hybridizer-basic-samples/tree/april_update/HybridizerBasicSamples_CUDA91/1.Simple/Builtin

Note this would work also for double, as we provide a polyfill for atomicAdd(double) (not natively supported in all cuda versions).
