### ISSUE TITLE
Continue loading subscriptionId

### ISSUE THREAD

**Issue by zhangyaqiang** [altimesh/hybridizer-basic-samples#55]
After I click the refresh license button, it continue loading without responding, is there anything wrong ?

**Comment by msofficial** [comment]
I also had to deal with this problem and I think the only thing I can propose is completely reinstalling Hybridizer. Make sure that you have removed Hybridizer completely as in my case otherwise Hybridizer would repair the current installation which didn't remove the error for me.

Hope that reinstalling works for you, Good luck with it.

**Comment by JeWaVe** [comment]
It’s probably a UI issue. Can you check after a restart of visual studio?

**Comment by JeWaVe** [comment]
resolved in our latest release ([1.1.9833](https://github.com/altimesh/hybridizer-basic-samples/releases/tag/1.1.9833))

**Comment by enshivam** [comment]
Facing the same issue Hybridizer version 1.3.0, and visual studio 2019. Please help.
